### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by stevenfollis** [GSIAzureCOE/SessionCatalog#4]

**Comment by stevenfollis** [comment]
Sorry @steffenv-msft  I can't delete this. :(

**Comment by KOBurf** [comment]
Hi guys, I don't see the issue that was closed. Was it just a test of the emergency broadcast system? If so, I got it LOL.

**Comment by stevenfollis** [comment]
Doh sorry about that @KOBurf! Was investing with @steffenv-msft; please ignore :)
